### ISSUE TITLE
MacOs support

### ISSUE THREAD

**Issue by maastrich** [MatthieuMv/openZia#1]
Will a macOs version will be available ?

**Comment by MatthieuMv** [comment]
There are no reason why it wouldn't compile on a mac system.
If you have any trouble compiling it, feel free to send me your log errors and I'll try to fix it ASAP.

**Comment by maastrich** [comment]
My bad, it seems to be a compatibility issue between C++ 17 and macOs 10.14.
I'm rechecking this and if it's fixed, I'll close the issue.

**Comment by MatthieuMv** [comment]
> My bad, it seems to be a compatibility issue between C++ 17 and macOs 10.14.
> I'm rechecking this and if it's fixed, I'll close the issue.

Did you have enough time to check mac os support ?

**Comment by MatthieuMv** [comment]
I'm closing this one as I don't have any error reports on macos.
