### ISSUE TITLE
World Example doesn't compile as is

### ISSUE THREAD

**Issue by Yooooomi** [MatthieuMv/openZia#11]
The full example doesn't compile, it seems like it's missing includes and semicolons on the second part of the `Hello world` example.

**Comment by MatthieuMv** [comment]
Done, thank you.

**Comment by Yooooomi** [comment]
It seems like setting a non existing `Header` with .get() = someValue crashes, didn't you mean `set()` ?

At this line in the `Hello` example `context.getResponse().getHeader().get("Content-Type") = "text/plain";`

**Comment by MatthieuMv** [comment]
Yes, I changed it last nigh, now the header uses a multimap, so I had not to emplace on Header::get to prevent missusing it.
Thank you

Edit: Update is done
