### ISSUE TITLE
Response encryption with SSL

### ISSUE THREAD

**Issue by jeremylvln** [MatthieuMv/openZia#14]
We should expose the raw file descriptor to the modules to permits encryption/decryption. Actually, only the server has the information.

**Comment by MatthieuMv** [comment]
Now it's fixed, I also removed the useless "encryption key" in Packet class.

**Comment by MatthieuMv** [comment]
Please notice that I added "onConnection" && "onDisconnection" callbacks for each modules (as dedicated virtual functions) to let you add more socket specific modules in your project.
All you need to do it derive theses function and call the Pipeline::onConnection/onDisconnection triggers functions to notify modules of any changes.
I'm currently updated md files to explain how it should be integrated. 

If you think that you may need another change to implement SSL or any other specific modules, please tell me what you could need, thank you.
