### ISSUE TITLE
[CI] Treat warnings as errors

### ISSUE THREAD

**Issue by rmaxi-me** [MatthieuMv/openZia#26]
Can you turn on the flags for treating warnings as errors on the continuous integration?  
It would avoid some bugs/crashes. (#24 for example)

Thanks :)

**Comment by MatthieuMv** [comment]
I added a OPENZIA_WERROR flag in openZia.cmake to let you add it for linux compilation, it is also added in travis' script.
I don't know much about MSVC so if you have time to work on adding compilations flags and add a werror-like one with the cmake variable it'd be great.

Thank you
