### ISSUE TITLE
Erreur dans le Hello World

### ISSUE THREAD

**Issue by docmurloc** [MatthieuMv/openZia#3]
Bonjour,

En lisant le Hello World de l'API j'ai remarqué que le constructeur utilisé de l'objet oZ::Context n'existait pas.

Dans la Class **Server**

```
void onPacketReceived(oZ::ByteArray &&buffer, const oZ::Endpoint endpoint) {
			oZ::Context context(std::move(buffer), endpoint);
			_pipeline.runPipeline(context);
			sendResponseToClient(context);
		}

```
voulais-tu dire:

```
void onPacketReceived(oZ::ByteArray &&buffer, const oZ::Endpoint endpoint) {
			oZ::Context context(oZ::Packet(std::move(buffer), endpoint));
			_pipeline.runPipeline(context);
			sendResponseToClient(context);
		}
```

**Comment by MatthieuMv** [comment]
Oui c'est bien une erreur de ma part, j'ai oublié de le changer après avoir modifié le constructeur, merci pour ton aide !

PS: J'ai push le changement
