### ISSUE TITLE
MSVC support

### ISSUE THREAD

**Issue by NicolasKeita** [MatthieuMv/openZia#9]
openZia does not compile using the Microsoft's compiler : MSVC

![Image of MSVC not compiling](https://zupimages.net/up/20/06/s89w.png)

Error Message :
`D:\documents\Apache-like\srcs\modules\Hello.cpp(11): error C2526: 'CreateModule': C linkage function cannot return C++ class 'std::shared_ptr<oZ::IModule>'`

The function CreateModule does not return a C type.

![Image of MSVC not compiling](https://zupimages.net/up/20/06/z4ge.png)

How to reproduce : 

Compile with Visual Studio's default compiler on Windows 10.

Possible solution : 
the CreateModule function **could return a raw pointer** to the class oZ::IModule  : `oZ::IModule *` instead of a `std::shared_ptr<oZ::IModule>`

I attempted to do it myself but miserably failed.

Thank you for this awesome API though.

**Comment by MatthieuMv** [comment]
The problem has been solved. This was a really specific MSVC issue.
I changed the CreateModule return for raw pointers that are directly encapsulated in a shared pointer after instantiation.

Thank you for you help !
